[package]
name = "jellyfin-import-library"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jellyfin_importer"
path = "src/main.rs"

[dependencies]
jf-import-library = { path = "../lib" }
reqwest = { version = "0.12.26", features = ["json", "blocking"] }
# futures = "0.3.31"
tokio = { version = "1", features = ["full"] }



