[package]
name = "jf-import-library"
version = "0.1.0"
edition = "2024"

[lib]
name = "jf_import_library"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.102"
dotenv-parser = "0.1.3"
etcetera = "0.11.0"
ignore = "0.4.25"
json = "0.12.4"
once_cell = "1.21.4"
regex = "1.12.2"
reqwest = { version = "0.12.26", features = ["json", "blocking"] }
urlencoding = "2.1.3"
tokio = { version = "1", features = ["full"] }
toml = "1.1.2"
serde = { version = "1.0.228", features = ["derive"] }

