[package]
name = "jf-import-library"
version = "0.1.0"
edition = "2024"

[lib]
name = "jf_importer"
path = "src/lib.rs"

[dependencies]
dotenv-parser = "0.1.3"
futures = "0.3.31"
ignore = "0.4.25"
json = "0.12.4"
lazy_static = "1.5.0"
regex = "1.12.2"
reqwest = { version = "0.12.26", features = ["json", "blocking"] }
urlencoding = "2.1.3"
tokio = { version = "1", features = ["full"] }

